# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
use_frameworks!

target '侧滑(navigationBar)连动demo' do

pod 'SwipeBack'                         ## 全能滑动手势返回
pod 'SnapKit'                           ## AutoLayout

end

